services:
  - type: web
    name: ona-spark
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_VERSION
        value: 9.x
      - key: NODE_ENV
        value: production
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envSecrets:
      - key: DATABASE_URL
        fromService:
          type: sqlite
          name: ona-spark-db
          property: connectionString
